class Constants:
    GET_WAAGENT_DATA_JOB_NAME: str = "get-waagent-data"
    JOB_NAMESPACE_LOCATION: int = 0
    JOB_COMPLETION_LOCATION: int = 2
    GET_WAAGENT_DATA_DEFAULT_NAMESPACE: str = "kube-system"
    SPOT_TOKEN: str = "SPOT_TOKEN"
    SPOT_ACCOUNT: str = "SPOT_ACCOUNT"
    CLUSTER_IDENTIFIER: str = "SPOT_CLUSTER_IDENTIFIER"
    LOG_SEVERITY: str = "SPOT_LOG_SEVERITY"
    HEADER_AUTHORIZATION: str = "Authorization"
    HEADER_CONTENT_TYPE: str = "Content-Type"
    SPOT_ACD_IDENTIFIER: str = "SPOT_ACD_IDENTIFIER"
    CONTENT_TYPE_APPLICATION_JSON: str = "application/json"
    BASE_OCEAN_AKS_API_URL: str = "https://api.spotinst.io/ocean/azure/k8s/cluster"
    CLUSTER_ROLL_ALREADY_IN_PROGRESS: str = "CLUSTER_ROLL_ALREADY_IN_PROGRESS"
    ROLL_IN_PROGRESS: str = "IN_PROGRESS"
    CLUSTER_HAS_NO_ACTIVE_INSTANCES: str = "CLUSTER_HAS_NO_ACTIVE_INSTANCES"

